dist: trusty
language: node_js
sudo: false
node_js:
  - 8

branches:
  only:
  - master

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest
  chrome: stable

install:
- yarn install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
- yarn run e2e --env chrome
- yarn run e2e --env firefox
- yarn run e2e --env electron
# - yarn run e2e --env phantomjs

cache:
  yarn: true
  directories:
  - node_modules
