dist: trusty
language: node_js
sudo: false
node_js:
  - 8

branches:
  only:
  - master

addons:
  firefox: "49.0"
  chrome: stable

install:
- yarn install

script:
- yarn run e2e:headless
- yarn run e2e:chrome
- yarn run e2e:firefox

cache:
  yarn: true
  directories:
  - node_modules
