dist: trusty
language: node_js
sudo: false
node_js:
  - 8

branches:
  only:
  - master

before_install:
- nvm install 8.9

install:
- yarn install

script:
- yarn run e2e:headless

cache:
  yarn: true
  directories:
  - node_modules
